# Taskfile.yml for building Scriptling CLI
version: "3"

vars:
  BIN_DIR: bin
  CLI_DIR: scriptling-cli
  LDFLAGS: -ldflags="-s -w -X github.com/paularlott/scriptling/build.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  BUILT_AT:
    sh: date +%Y%m%d.%H%M%S%z
  VERSION:
    sh: go run ./tools/getversion

tasks:
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}

  build:
    desc: Build for current platform
    dir: scriptling-cli
    cmds:
      - go build {{.LDFLAGS}} -o ../{{.BIN_DIR}}/scriptling .

  build-platforms:
    desc: Build for all platforms (Linux, macOS, Windows)
    deps:
      [
        build-linux-amd64,
        build-linux-arm64,
        build-darwin-amd64,
        build-darwin-arm64,
        build-windows-amd64,
        build-windows-arm64,
      ]

  build-all:
    desc: Build for all platforms
    deps: [clean]
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - task: build-platforms
      - task: create-zips

  create-zips:
    desc: Create ZIP files for all platforms
    cmds:
      - cd {{.BIN_DIR}} && cp scriptling-darwin-amd64 scriptling && zip scriptling-darwin-amd64.zip scriptling && rm scriptling
      - cd {{.BIN_DIR}} && cp scriptling-darwin-arm64 scriptling && zip scriptling-darwin-arm64.zip scriptling && rm scriptling
      - cd {{.BIN_DIR}} && cp scriptling-linux-amd64 scriptling && zip scriptling-linux-amd64.zip scriptling && rm scriptling
      - cd {{.BIN_DIR}} && cp scriptling-linux-arm64 scriptling && zip scriptling-linux-arm64.zip scriptling && rm scriptling
      - cd {{.BIN_DIR}} && cp scriptling-windows-amd64.exe scriptling.exe && zip scriptling-windows-amd64.zip scriptling.exe && rm scriptling.exe
      - cd {{.BIN_DIR}} && cp scriptling-windows-arm64.exe scriptling.exe && zip scriptling-windows-arm64.zip scriptling.exe && rm scriptling.exe

  build-linux-amd64:
    desc: Build for Linux AMD64
    dir: scriptling-cli
    cmds:
      - GOOS=linux GOARCH=amd64 go build {{.LDFLAGS}} -o ../{{.BIN_DIR}}/scriptling-linux-amd64 .

  build-linux-arm64:
    desc: Build for Linux ARM64
    dir: scriptling-cli
    cmds:
      - GOOS=linux GOARCH=arm64 go build {{.LDFLAGS}} -o ../{{.BIN_DIR}}/scriptling-linux-arm64 .

  build-darwin-amd64:
    desc: Build for macOS AMD64
    dir: scriptling-cli
    cmds:
      - GOOS=darwin GOARCH=amd64 go build {{.LDFLAGS}} -o ../{{.BIN_DIR}}/scriptling-darwin-amd64 .

  build-darwin-arm64:
    desc: Build for macOS ARM64
    dir: scriptling-cli
    cmds:
      - GOOS=darwin GOARCH=arm64 go build {{.LDFLAGS}} -o ../{{.BIN_DIR}}/scriptling-darwin-arm64 .

  build-windows-amd64:
    desc: Build for Windows AMD64
    dir: scriptling-cli
    cmds:
      - GOOS=windows GOARCH=amd64 go build {{.LDFLAGS}} -o ../{{.BIN_DIR}}/scriptling-windows-amd64.exe .

  build-windows-arm64:
    desc: Build for Windows ARM64
    dir: scriptling-cli
    cmds:
      - GOOS=windows GOARCH=arm64 go build {{.LDFLAGS}} -o ../{{.BIN_DIR}}/scriptling-windows-arm64.exe .

  test:
    desc: Run tests
    cmds:
      - go test ./...

  homebrew-formula:
    desc: Generate the Homebrew formula
    cmds:
      - go run ./scripts/homebrew-formula/ > ../homebrew-tap/Formula/scriptling.rb

  release:
    desc: Tag the version and create GitHub release with all platform binaries
    deps: [build-all]
    cmds:
      - |
        # Check if tag exists
        if git tag -l v{{.VERSION}} | grep -q v{{.VERSION}}; then
          echo "Tag v{{.VERSION}} already exists, skipping tag creation"
        else
          echo "Creating tag v{{.VERSION}}"
          git tag -a v{{.VERSION}} -m "Release {{.VERSION}}"
          git push origin v{{.VERSION}}
        fi
        # Create release and upload zip files only
        gh release create v{{.VERSION}} -t "Release {{.VERSION}}" -n "Scriptling {{.VERSION}}" {{.BIN_DIR}}/*.zip
      - task: homebrew-formula
