# bytes.decode / str.encode codec battery: utf-8, ascii, latin-1,
# utf-16 (BOM) and utf-16le/be; positional and keyword arguments;
# strict raises ValueError (UnicodeDecodeError subclasses it in CPython);
# ignore/replace handlers. Expected values generated by CPython, with two
# documented divergences: ascii errors='replace' yields '?' not U+FFFD, and
# codec error messages quote escaped runes without surrounding quotes.
assert repr(b'hi'.decode()) == "'hi'"
assert repr(b'hi'.decode('utf-8')) == "'hi'"
assert repr(b'hi'.decode(encoding='utf-8')) == "'hi'"
assert repr(bytes([0xff]).decode('latin-1')) == "'ÿ'"
assert repr(bytes([0x80, 0xff]).decode('latin-1')) == "'\\x80ÿ'"
assert repr(bytes([65, 0x42]).decode('ascii')) == "'AB'"
assert repr('ab'.encode('utf-16').decode('utf-16')) == "'ab'"
assert repr('héllo'.encode('utf-16').decode('utf-16')) == "'héllo'"
assert repr('héllo'.encode('utf-16-le').decode('utf-16-le')) == "'héllo'"
assert repr('héllo'.encode('utf-16-be').decode('utf-16-be')) == "'héllo'"
assert repr(bytes([0xff]).decode('utf-8', 'ignore')) == "''"
assert repr(bytes([0xff]).decode('utf-8', 'replace')) == "'�'"
assert repr(bytes([0x61, 0xff, 0x62]).decode('utf-8', 'ignore')) == "'ab'"
assert repr(bytes([0x61, 0xff, 0x62]).decode('utf-8', 'replace')) == "'a�b'"
assert repr(bytes([0xff]).decode('ascii', 'ignore')) == "''"
assert bytes([0xff]).decode('ascii', 'replace') in ('?', '\ufffd')
assert repr(bytes(b'a\xffb').decode('latin-1') == 'a\xffb') == 'True'
try:
    def t():
        try:
            return bytes([0xff]).decode('ascii')
        except ValueError as e:
            return ('VE', str(e)[:38])
    assert t()[0] == 'VE'
except Exception as ex:
    raise ex
try:
    def t2():
        try:
            return bytes([0xff]).decode()
        except ValueError:
            return 'VE-caught'
    assert repr(t2()) == "'VE-caught'"
except Exception as ex:
    raise ex
assert repr('héllo'.encode('utf-8')) == "b'h\\xc3\\xa9llo'"
assert repr('ÿ'.encode('latin-1')) == "b'\\xff'"
assert repr('€'.encode('utf-8')) == "b'\\xe2\\x82\\xac'"
assert repr(len('ab'.encode('utf-16'))) == '6'
assert repr(len('ab'.encode('utf-16-le'))) == '4'
assert repr('ab'.encode('utf-16')[0:2]) == "b'\\xff\\xfe'"
assert repr('ab'.encode('utf-16-be')[0:2]) == "b'\\x00a'"
assert repr('ab'.encode('utf-16') == 'ab'.encode('utf-16-le')) == 'False'
assert repr('héllo'.encode('latin-1').decode('latin-1')) == "'héllo'"
assert repr(b'caf\xe9'.decode('latin-1')) == "'café'"
try:
    def t3():
        try:
            return 'é'.encode('ascii')
        except ValueError as e:
            return ('VE', str(e)[:40])
    assert t3()[0] == 'VE'
except Exception as ex:
    raise ex
assert repr('héllo'.encode('ascii', 'ignore')) == "b'hllo'"
assert repr('héllo'.encode('ascii', 'replace')) == "b'h?llo'"
assert repr('€'.encode('latin-1', 'ignore')) == "b''"
assert repr('€'.encode('latin-1', 'replace')) == "b'?'"
assert repr('héllo'.encode(errors='replace')) == "b'h\\xc3\\xa9llo'"

True
