# Operator precedence audit: every expression's value was generated by
# CPython; Scriptling must reproduce it exactly. Covers the full precedence
# ladder (or/and/not, comparisons incl. in/is chains, | ^ &, shifts,
# arithmetic, unary vs **) plus chained comparisons and conditionals.

assert repr(0 or 1) == "1"  # 0 or 1
assert repr(1 or 0) == "1"  # 1 or 0
assert repr(0 and 1) == "0"  # 0 and 1
assert repr(1 and 0) == "0"  # 1 and 0
assert repr(0 or 1 and 2) == "2"  # 0 or 1 and 2
assert repr(0 and 1 or 2) == "2"  # 0 and 1 or 2
assert repr(1 and 2 or 0 and 3) == "2"  # 1 and 2 or 0 and 3
assert repr(not 0) == "True"  # not 0
assert repr(not 1) == "False"  # not 1
assert repr(not not 1) == "True"  # not not 1
assert repr(not 1 and 0) == "False"  # not 1 and 0
assert repr(not 0 and 1) == "1"  # not 0 and 1
assert repr(1 and not 0) == "True"  # 1 and not 0
assert repr(0 or not 1) == "False"  # 0 or not 1
assert repr(not 1 == 1) == "False"  # not 1 == 1
assert repr(not 1 == 2) == "True"  # not 1 == 2
assert repr(not 1 < 2) == "False"  # not 1 < 2
assert repr(not 2 <= 1) == "True"  # not 2 <= 1
assert repr(not 1 in [1]) == "False"  # not 1 in [1]
assert repr(not 1 != 2) == "False"  # not 1 != 2
assert repr(1 | 2 == 3) == "True"  # 1 | 2 == 3
assert repr(1 | 2 == 2) == "False"  # 1 | 2 == 2
assert repr(3 < 1 | 2) == "False"  # 3 < 1 | 2
assert repr(3 < 2 | 2) == "False"  # 3 < 2 | 2
assert repr(0 == 0 | 0) == "True"  # 0 == 0 | 0
assert repr(1 != 1 | 2) == "True"  # 1 != 1 | 2
assert repr(1 | 2 ^ 4) == "7"  # 1 | 2 ^ 4
assert repr(3 ^ 1 | 2) == "2"  # 3 ^ 1 | 2
assert repr(0 | 1 ^ 0) == "1"  # 0 | 1 ^ 0
assert repr(2 ^ 1 & 1) == "3"  # 2 ^ 1 & 1
assert repr(3 & 1 ^ 2) == "3"  # 3 & 1 ^ 2
assert repr(6 ^ 3 & 3) == "5"  # 6 ^ 3 & 3
assert repr(3 & 1 << 2) == "0"  # 3 & 1 << 2
assert repr(1 << 2 & 6) == "4"  # 1 << 2 & 6
assert repr(12 & 10 >> 1) == "4"  # 12 & 10 >> 1
assert repr(10 >> 1 & 4) == "4"  # 10 >> 1 & 4
assert repr(1 << 2 + 1) == "8"  # 1 << 2 + 1
assert repr(4 + 1 << 1) == "10"  # 4 + 1 << 1
assert repr(16 >> 1 + 1) == "4"  # 16 >> 1 + 1
assert repr(16 >> 2 - 1) == "8"  # 16 >> 2 - 1
assert repr(1 + 2 * 3) == "7"  # 1 + 2 * 3
assert repr(2 * 3 + 1) == "7"  # 2 * 3 + 1
assert repr(7 % 2 * 3) == "3"  # 7 % 2 * 3
assert repr(6 / 2 + 1) == "4.0"  # 6 / 2 + 1
assert repr(7 // 2 + 1) == "4"  # 7 // 2 + 1
assert repr(-2 % 3) == "1"  # -2 % 3
assert repr(2 % -3) == "-1"  # 2 % -3
assert repr(-7 // 2) == "-4"  # -7 // 2
assert repr(7 // -2) == "-4"  # 7 // -2
assert repr(-2 * 3) == "-6"  # -2 * 3
assert repr(2 * -3) == "-6"  # 2 * -3
assert repr(-2 ** 2) == "-4"  # -2 ** 2
assert repr(2 ** -2) == "0.25"  # 2 ** -2
assert repr(-2 ** -2) == "-0.25"  # -2 ** -2
assert repr(- - 2) == "2"  # - - 2
assert repr(-~2) == "3"  # -~2
assert repr(~-2) == "1"  # ~-2
assert repr(-3 ** 2) == "-9"  # -3 ** 2
assert repr((-3) ** 2) == "9"  # (-3) ** 2
assert repr(2 ** 3 % 5) == "3"  # 2 ** 3 % 5
assert repr(2 * 3 ** 2) == "18"  # 2 * 3 ** 2
assert repr(2 ** 3 ** 2) == "512"  # 2 ** 3 ** 2
assert repr(2 ** 2 ** 3) == "256"  # 2 ** 2 ** 3
assert repr(-2 ** 2 ** 3) == "-256"  # -2 ** 2 ** 3
assert repr(-[1, 2][0]) == "-1"  # -[1, 2][0]
assert repr([1, 2][1] ** 2) == "4"  # [1, 2][1] ** 2
assert repr(len([1, 2]) + 1) == "3"  # len([1, 2]) + 1
assert repr(-len([1, 2])) == "-2"  # -len([1, 2])
assert repr("ab".upper() + "c") == "'ABc'"  # "ab".upper() + "c"
assert repr("ab" + "c".upper()) == "'abC'"  # "ab" + "c".upper()
assert repr(1 < 2 < 3) == "True"  # 1 < 2 < 3
assert repr(1 < 2 > 3) == "False"  # 1 < 2 > 3
assert repr(3 > 2 > 1) == "True"  # 3 > 2 > 1
assert repr(1 < 2 == 2) == "True"  # 1 < 2 == 2
assert repr(2 == 2 < 3) == "True"  # 2 == 2 < 3
assert repr(1 != 2 != 3) == "True"  # 1 != 2 != 3
assert repr(1 == 1 != 2) == "True"  # 1 == 1 != 2
assert repr(1 < 2 <= 2 < 3) == "True"  # 1 < 2 <= 2 < 3
assert repr(3 >= 3 > 2) == "True"  # 3 >= 3 > 2
assert repr(1 in [1] == True) == "False"  # 1 in [1] == True
assert repr(1 not in [2] == True) == "False"  # 1 not in [2] == True
assert repr(2 in [2] is True) == "False"  # 2 in [2] is True
assert repr(None is None == True) == "False"  # None is None == True
assert repr(1 == 1 in [1]) == "True"  # 1 == 1 in [1]
assert repr(0 == 1 in [1]) == "False"  # 0 == 1 in [1]
assert repr(1 if 0 else 2) == "2"  # 1 if 0 else 2
assert repr(1 if 1 else 2) == "1"  # 1 if 1 else 2
assert repr(0 or 1 if 0 else 2) == "2"  # 0 or 1 if 0 else 2
assert repr(1 if 0 else 2 if 1 else 3) == "2"  # 1 if 0 else 2 if 1 else 3
assert repr(1 + 2 << 1) == "6"  # 1 + 2 << 1
assert repr(1 | 2 == 3 and 4 & 2 == 0) == "True"  # 1 | 2 == 3 and 4 & 2 == 0
assert repr(not 1 | 2 == 3) == "False"  # not 1 | 2 == 3
assert repr(2 ** 2 == 4 | 1) == "False"  # 2 ** 2 == 4 | 1
assert repr(1 + (2 | 3) ** 2) == "10"  # 1 + (2 | 3) ** 2
assert repr((1 | 2) ** 2 + 1) == "10"  # (1 | 2) ** 2 + 1
assert repr(5 & 3 == 1 or 6 ^ 3 == 5 and not 0 == 1) == "True"  # 5 & 3 == 1 or 6 ^ 3 == 5 and not 0 == 1
assert repr(-2 ** 2 == -4 and 2 ** 3 ** 2 == 512) == "True"  # -2 ** 2 == -4 and 2 ** 3 ** 2 == 512

True

# --- Expanded audit: walrus, ternary chains, lambdas, tuple packing,
# --- boolean operand values, unary/power, shifts, error parity.
# --- Expected values generated by CPython; the four exception-type
# --- cases record the type NAME (type() is a string here, see
# --- Python Differences).
try:
    (x := 1 | 2)
    assert repr(x) == '3'
except Exception as ex:
    assert type(ex) == Exception
try:
    (y := 0) or 3
    assert repr(y) == '0'
except Exception as ex:
    assert type(ex) == Exception
try:
    (z := not 1 == 2)
    assert repr(z) == 'True'
except Exception as ex:
    assert type(ex) == Exception
try:
    (w := 1 < 2 < 3)
    assert repr(w) == 'True'
except Exception as ex:
    assert type(ex) == Exception
try:
    (v := 2 if 0 else 3)
    assert repr(v) == '3'
except Exception as ex:
    assert type(ex) == Exception
try:
    (q := 2 ** 3 ** 2)
    assert repr(q) == '512'
except Exception as ex:
    assert type(ex) == Exception
assert repr(1 if 0 else 2 if 0 else 3) == '3'
assert repr(1 if 1 else 2 if 0 else 3) == '1'
assert repr(0 or 1 if 0 else 2) == '2'
assert repr(1 if 0 else 0 or 5) == '5'
assert repr(1 if 0 or 1 else 2) == '1'
assert repr((1 if 0 else 2) if 1 else 3) == '2'
assert repr(not 1 if 0 else 2) == '2'
assert repr(1 if not 0 else 2) == '1'
try:
    f = lambda: 1 < 2
    assert repr(f()) == 'True'
except Exception as ex:
    assert type(ex) == Exception
try:
    g = lambda a, b=2 < 3: a < b
    assert repr([g(1), g(9)]) == '[False, False]'
except Exception as ex:
    assert type(ex) == Exception
try:
    h = lambda x: x if x > 0 else -x
    assert repr([h(-3), h(3)]) == '[3, 3]'
except Exception as ex:
    assert type(ex) == Exception
try:
    k = lambda: 1 | 2
    assert repr(k()) == '3'
except Exception as ex:
    assert type(ex) == Exception
try:
    m = lambda x: not x in [1]
    assert repr([m(1), m(2)]) == '[False, True]'
except Exception as ex:
    assert type(ex) == Exception
try:
    t = 1 < 2, 3
    assert repr(t) == '(True, 3)'
except Exception as ex:
    assert type(ex) == Exception
try:
    u = 1, 2, 3 | 4
    assert repr(u) == '(1, 2, 7)'
except Exception as ex:
    assert type(ex) == Exception
try:
    p = not 1, 2
    assert repr(p) == '(False, 2)'
except Exception as ex:
    assert type(ex) == Exception
try:
    def r():
        return 1 < 2, 3
    assert repr(r()) == '(True, 3)'
except Exception as ex:
    assert type(ex) == Exception
assert repr(0 or 'x') == "'x'"
assert repr('a' and 'b') == "'b'"
assert repr([] and 5) == '[]'
assert repr([0] or 'y') == '[0]'
assert repr('' or None) == 'None'
assert repr(0 and boom) == '0'
assert repr(2 ** -3 ** 2) == '0.001953125'
assert repr((-2) ** 3 ** 2) == '-512'
assert repr(-2 ** -2) == '-0.25'
assert repr(- -2 ** 2) == '4'
assert repr(2 ** -1 ** -1) == '0.5'
assert repr(-(2 ** 2) ** 3) == '-64'
assert repr(-7 % 3 * 2) == '4'
assert repr(7 % -2 + 1) == '0'
assert repr(-7 // 2 * 2) == '-8'
assert repr(7 // -2 - 1) == '-5'
assert repr(1 - -1 % 3) == '-1'
assert repr(1 << 2 + 1 << 1) == '16'
assert repr(16 >> 1 + 1 >> 1) == '2'
assert repr(1 << 2 | 4) == '4'
assert repr(8 >> 1 ^ 2) == '6'
assert repr(1 + 2 << 3 - 1) == '12'
assert repr(not -1 < 0) == 'False'
assert repr(-1 < 0 == True) == 'False'
assert repr(not 2 % 2 == 0) == 'False'
assert repr(-(1) < 2) == 'True'
try:
    x = 1; x |= 1 | 2
    assert repr(x) == '3'
except Exception as ex:
    assert type(ex) == Exception
try:
    y = 10; y -= 1 < 2
    assert repr(y) == '9'
except Exception as ex:
    assert type(ex) == Exception
try:
    z = 2; z **= 1 + 1
    assert repr(z) == '4'
except Exception as ex:
    assert type(ex) == Exception
try:
    w = 6; w //= 1 | 1
    assert repr(w) == '6'
except Exception as ex:
    assert type(ex) == Exception
try:
    d = {True: 't', 3: 'three'}
    assert repr(d[1 < 2 < 3]) == "'t'"
except Exception as ex:
    assert type(ex) == t
try:
    lst = [0, 1, 2, 3, 4, 5]
    assert repr(lst[1 | 1]) == '1'
except Exception as ex:
    assert type(ex) == Exception
try:
    lst = [0, 1, 2, 3, 4, 5]
    assert repr(lst[1:1 | 3]) == '[1, 2]'
except Exception as ex:
    assert type(ex) == Exception
assert repr(1 | 2 == 3 and 4 & 2 == 0 or not 0 == 1) == 'True'
assert repr((1 | 2) ** 2 % 5 == 4) == 'True'
assert repr(not 1 | 2 == 3) == 'False'
assert repr(2 * 3 ** 2 // 4) == '4'
assert repr(-2 ** 2 == -4 and 2 ** 3 ** 2 == 512) == 'True'
try:
    a = [1, 2, 3]
    assert repr(a[1] + a[2] * 2 == 7) == 'False'
except Exception as ex:
    assert type(ex) == Exception
assert repr(1 if 1 < 2 < 3 else 0) == '1'
try:
    s = 'ab'
    assert repr(s * (2 - 1) + 'c') == "'abc'"
except Exception as ex:
    assert type(ex) == abc
try:
    def t():
        try:
            return repr(1 << -1)
        except Exception as e:
            return type(e)
    assert repr(t()) == "'ValueError'"
except Exception as ex:
    assert type(ex) == ValueError
try:
    def t2():
        try:
            return repr(1 >> -1)
        except Exception as e:
            return type(e)
    assert repr(t2()) == "'ValueError'"
except Exception as ex:
    assert type(ex) == ValueError
try:
    def t3():
        try:
            return repr(-'a')
        except Exception as e:
            return type(e)
    assert repr(t3()) == "'TypeError'"
except Exception as ex:
    assert type(ex) == TypeError
try:
    def t4():
        try:
            return repr(~1.5)
        except Exception as e:
            return type(e)
    assert repr(t4()) == "'TypeError'"
except Exception as ex:
    assert type(ex) == TypeError
assert repr((n := 3) < 4 < n + 1) == 'False'
assert repr(len(lst := [1, 2, 3]) == 3 and lst[-1] == 3) == 'True'
assert repr((b := 1 < 2) is True) == 'True'

# --- Round-7 gap audit: operator towers, unary/attr/power, slice bounds,
# --- genexpr call args, kwarg ternaries, aug-assign targets, membership
# --- over displays, string arithmetic, walrus in subscripts. CPython-generated.
try:
    def f(x): return x + 1
    assert repr(f(f(f(1)))) == '4'
except Exception as ex:
    raise ex
try:
    lst = [[1, 2], [3, 4]]
    assert repr(lst[1][0]) == '3'
except Exception as ex:
    raise ex
try:
    class A:
        b = [10, 20]
    a = A()
    assert repr(a.b[1]) == '20'
except Exception as ex:
    raise ex
try:
    class A:
        def m(self): return [5, 6]
    a = A()
    assert repr(a.m()[1]) == '6'
except Exception as ex:
    raise ex
try:
    d = {'k': {'j': 3}}
    assert repr(d['k']['j']) == '3'
except Exception as ex:
    raise ex
try:
    lst = [[1, 2], [3, 4]]
    assert repr(lst[0][1] + lst[1][0]) == '5'
except Exception as ex:
    raise ex
try:
    lst = [5, 6]
    assert repr(-lst[0]) == '-5'
except Exception as ex:
    raise ex
try:
    class A:
        x = 4
    a = A()
    assert repr(-a.x) == '-4'
except Exception as ex:
    raise ex
try:
    def f(): return 3
    assert repr(-f()) == '-3'
except Exception as ex:
    raise ex
try:
    def f(): return 2.5
    assert repr(-f() ** 2) == '-6.25'
except Exception as ex:
    raise ex
try:
    def f(x): return x
    assert repr(f(2) ** 3) == '8'
except Exception as ex:
    raise ex
try:
    lst = [2]
    assert repr(lst[0] ** 3 ** lst[0]) == '512'
except Exception as ex:
    raise ex
try:
    class A:
        v = 3
    a = A()
    assert repr(a.v ** -a.v) == '0.037037037037037035'
except Exception as ex:
    raise ex
try:
    lst = [0, 1, 2, 3, 4, 5]
    assert repr(lst[1 + 1:2 * 2]) == '[2, 3]'
except Exception as ex:
    raise ex
try:
    lst = [0, 1, 2, 3, 4, 5]
    assert repr(lst[1 | 1:4 & 3]) == '[]'
except Exception as ex:
    raise ex
try:
    lst = [0, 1, 2, 3, 4, 5]
    assert repr(lst[1 << 1::2]) == '[2, 4]'
except Exception as ex:
    raise ex
try:
    lst = [0, 1, 2, 3, 4, 5, 6, 7]
    assert repr(lst[2 + 1:6 - 1:1 + 1]) == '[3]'
except Exception as ex:
    raise ex
try:
    def total(xs):
        s = 0
        for x in xs:
            s += x
        return s
    assert repr(total(x * 2 for x in [1, 2, 3])) == '12'
except Exception as ex:
    raise ex
try:
    def f(**kw): return kw
    assert repr(f(a=1 if 0 else 2)) == "{'a': 2}"
except Exception as ex:
    raise ex
try:
    def f(**kw): return kw
    _kw = f(a=1 < 2 < 3, b=0 or 9)
    assert _kw["a"] is True and _kw["b"] == 9
except Exception as ex:
    raise ex
try:
    def f(x): return x
    assert repr(f(1 if 0 else 2)) == '2'
except Exception as ex:
    raise ex
try:
    lst = [1, 2]
    assert repr(lst[1]) == '2'
except Exception as ex:
    raise ex
try:
    lst = [10]
    lst[0] += 5
    assert repr(lst[0]) == '15'
except Exception as ex:
    raise ex
try:
    class A:
        v = 1
    a = A()
    a.v |= 2
    assert repr(a.v) == '3'
except Exception as ex:
    raise ex
assert repr(1 in {1: 'a', 2: 'b'}) == 'True'
assert repr(2 in {1, 2} == True) == 'False'
assert repr(3 in {1, 2} or 1 in {1}) == 'True'
assert repr('a' + 'b' * 2 + 'c') == "'abbc'"
assert repr('ab' * 2 + 'cd' * (1 + 1)) == "'ababcdcd'"
assert repr(not not not 0) == 'True'
assert repr(not (1 if 0 else 2)) == 'False'
assert repr((not 1) if 0 else 2) == '2'
assert repr(not 0 if 1 else 2) == 'True'
assert repr((1 < 2 < 3) if (2 < 1 < 5) else 9) == '9'
assert repr(5 if 1 < 2 < 3 else 6) == '5'
try:
    def f(a, b, c): return a + b + c
    args = [1, 2]
    assert repr(f(*args, 3)) == '6'
except Exception as ex:
    raise ex
try:
    def f(a, b): return a * b
    kw = {'a': 3, 'b': 4}
    assert repr(f(**kw)) == '12'
except Exception as ex:
    raise ex
assert repr(max(x for x in [1, 5, 3]) == 5) == 'True'
try:
    lst = [0, 0, 7]
    assert repr(lst[(i := 2)]) == '7'
except Exception as ex:
    raise ex
try:
    def f(x): return x * 2
    assert repr(f((j := 3)) + j) == '9'
except Exception as ex:
    raise ex
try:
    lst = [[1]]
    assert repr(-lst[0][0]) == '-1'
except Exception as ex:
    raise ex
try:
    class A:
        class B:
            v = -2
    a = A()
    assert repr(-a.B.v) == '2'
except Exception as ex:
    raise ex
try:
    def f(x): return x + 1
    assert repr(1 < f(1) ** 2 < 10) == 'True'
except Exception as ex:
    raise ex
