# Operator precedence audit: every expression's value was generated by
# CPython; Scriptling must reproduce it exactly. Covers the full precedence
# ladder (or/and/not, comparisons incl. in/is chains, | ^ &, shifts,
# arithmetic, unary vs **) plus chained comparisons and conditionals.

assert repr(0 or 1) == "1"  # 0 or 1
assert repr(1 or 0) == "1"  # 1 or 0
assert repr(0 and 1) == "0"  # 0 and 1
assert repr(1 and 0) == "0"  # 1 and 0
assert repr(0 or 1 and 2) == "2"  # 0 or 1 and 2
assert repr(0 and 1 or 2) == "2"  # 0 and 1 or 2
assert repr(1 and 2 or 0 and 3) == "2"  # 1 and 2 or 0 and 3
assert repr(not 0) == "True"  # not 0
assert repr(not 1) == "False"  # not 1
assert repr(not not 1) == "True"  # not not 1
assert repr(not 1 and 0) == "False"  # not 1 and 0
assert repr(not 0 and 1) == "1"  # not 0 and 1
assert repr(1 and not 0) == "True"  # 1 and not 0
assert repr(0 or not 1) == "False"  # 0 or not 1
assert repr(not 1 == 1) == "False"  # not 1 == 1
assert repr(not 1 == 2) == "True"  # not 1 == 2
assert repr(not 1 < 2) == "False"  # not 1 < 2
assert repr(not 2 <= 1) == "True"  # not 2 <= 1
assert repr(not 1 in [1]) == "False"  # not 1 in [1]
assert repr(not 1 != 2) == "False"  # not 1 != 2
assert repr(1 | 2 == 3) == "True"  # 1 | 2 == 3
assert repr(1 | 2 == 2) == "False"  # 1 | 2 == 2
assert repr(3 < 1 | 2) == "False"  # 3 < 1 | 2
assert repr(3 < 2 | 2) == "False"  # 3 < 2 | 2
assert repr(0 == 0 | 0) == "True"  # 0 == 0 | 0
assert repr(1 != 1 | 2) == "True"  # 1 != 1 | 2
assert repr(1 | 2 ^ 4) == "7"  # 1 | 2 ^ 4
assert repr(3 ^ 1 | 2) == "2"  # 3 ^ 1 | 2
assert repr(0 | 1 ^ 0) == "1"  # 0 | 1 ^ 0
assert repr(2 ^ 1 & 1) == "3"  # 2 ^ 1 & 1
assert repr(3 & 1 ^ 2) == "3"  # 3 & 1 ^ 2
assert repr(6 ^ 3 & 3) == "5"  # 6 ^ 3 & 3
assert repr(3 & 1 << 2) == "0"  # 3 & 1 << 2
assert repr(1 << 2 & 6) == "4"  # 1 << 2 & 6
assert repr(12 & 10 >> 1) == "4"  # 12 & 10 >> 1
assert repr(10 >> 1 & 4) == "4"  # 10 >> 1 & 4
assert repr(1 << 2 + 1) == "8"  # 1 << 2 + 1
assert repr(4 + 1 << 1) == "10"  # 4 + 1 << 1
assert repr(16 >> 1 + 1) == "4"  # 16 >> 1 + 1
assert repr(16 >> 2 - 1) == "8"  # 16 >> 2 - 1
assert repr(1 + 2 * 3) == "7"  # 1 + 2 * 3
assert repr(2 * 3 + 1) == "7"  # 2 * 3 + 1
assert repr(7 % 2 * 3) == "3"  # 7 % 2 * 3
assert repr(6 / 2 + 1) == "4.0"  # 6 / 2 + 1
assert repr(7 // 2 + 1) == "4"  # 7 // 2 + 1
assert repr(-2 % 3) == "1"  # -2 % 3
assert repr(2 % -3) == "-1"  # 2 % -3
assert repr(-7 // 2) == "-4"  # -7 // 2
assert repr(7 // -2) == "-4"  # 7 // -2
assert repr(-2 * 3) == "-6"  # -2 * 3
assert repr(2 * -3) == "-6"  # 2 * -3
assert repr(-2 ** 2) == "-4"  # -2 ** 2
assert repr(2 ** -2) == "0.25"  # 2 ** -2
assert repr(-2 ** -2) == "-0.25"  # -2 ** -2
assert repr(- - 2) == "2"  # - - 2
assert repr(-~2) == "3"  # -~2
assert repr(~-2) == "1"  # ~-2
assert repr(-3 ** 2) == "-9"  # -3 ** 2
assert repr((-3) ** 2) == "9"  # (-3) ** 2
assert repr(2 ** 3 % 5) == "3"  # 2 ** 3 % 5
assert repr(2 * 3 ** 2) == "18"  # 2 * 3 ** 2
assert repr(2 ** 3 ** 2) == "512"  # 2 ** 3 ** 2
assert repr(2 ** 2 ** 3) == "256"  # 2 ** 2 ** 3
assert repr(-2 ** 2 ** 3) == "-256"  # -2 ** 2 ** 3
assert repr(-[1, 2][0]) == "-1"  # -[1, 2][0]
assert repr([1, 2][1] ** 2) == "4"  # [1, 2][1] ** 2
assert repr(len([1, 2]) + 1) == "3"  # len([1, 2]) + 1
assert repr(-len([1, 2])) == "-2"  # -len([1, 2])
assert repr("ab".upper() + "c") == "'ABc'"  # "ab".upper() + "c"
assert repr("ab" + "c".upper()) == "'abC'"  # "ab" + "c".upper()
assert repr(1 < 2 < 3) == "True"  # 1 < 2 < 3
assert repr(1 < 2 > 3) == "False"  # 1 < 2 > 3
assert repr(3 > 2 > 1) == "True"  # 3 > 2 > 1
assert repr(1 < 2 == 2) == "True"  # 1 < 2 == 2
assert repr(2 == 2 < 3) == "True"  # 2 == 2 < 3
assert repr(1 != 2 != 3) == "True"  # 1 != 2 != 3
assert repr(1 == 1 != 2) == "True"  # 1 == 1 != 2
assert repr(1 < 2 <= 2 < 3) == "True"  # 1 < 2 <= 2 < 3
assert repr(3 >= 3 > 2) == "True"  # 3 >= 3 > 2
assert repr(1 in [1] == True) == "False"  # 1 in [1] == True
assert repr(1 not in [2] == True) == "False"  # 1 not in [2] == True
assert repr(2 in [2] is True) == "False"  # 2 in [2] is True
assert repr(None is None == True) == "False"  # None is None == True
assert repr(1 == 1 in [1]) == "True"  # 1 == 1 in [1]
assert repr(0 == 1 in [1]) == "False"  # 0 == 1 in [1]
assert repr(1 if 0 else 2) == "2"  # 1 if 0 else 2
assert repr(1 if 1 else 2) == "1"  # 1 if 1 else 2
assert repr(0 or 1 if 0 else 2) == "2"  # 0 or 1 if 0 else 2
assert repr(1 if 0 else 2 if 1 else 3) == "2"  # 1 if 0 else 2 if 1 else 3
assert repr(1 + 2 << 1) == "6"  # 1 + 2 << 1
assert repr(1 | 2 == 3 and 4 & 2 == 0) == "True"  # 1 | 2 == 3 and 4 & 2 == 0
assert repr(not 1 | 2 == 3) == "False"  # not 1 | 2 == 3
assert repr(2 ** 2 == 4 | 1) == "False"  # 2 ** 2 == 4 | 1
assert repr(1 + (2 | 3) ** 2) == "10"  # 1 + (2 | 3) ** 2
assert repr((1 | 2) ** 2 + 1) == "10"  # (1 | 2) ** 2 + 1
assert repr(5 & 3 == 1 or 6 ^ 3 == 5 and not 0 == 1) == "True"  # 5 & 3 == 1 or 6 ^ 3 == 5 and not 0 == 1
assert repr(-2 ** 2 == -4 and 2 ** 3 ** 2 == 512) == "True"  # -2 ** 2 == -4 and 2 ** 3 ** 2 == 512

True
