# Round-10 scatter: datetime arithmetic, math + format specs, hash/encode
# round-trips, deep itertools/functools, textwrap/html/url, dict views,
# str.format, escapes. Expected values generated by CPython. Excluded:
# datetime/date repr format and type()-as-string (documented cosmetic
# divergences).
try:
    import datetime
    assert repr(datetime.timedelta(hours=25).total_seconds()) == '90000.0'
except Exception as ex:
    raise ex
try:
    import datetime
    assert repr((datetime.datetime(2026, 10, 6) - datetime.datetime(2026, 10, 1)).days) == '5'
except Exception as ex:
    raise ex
try:
    import datetime
    d = datetime.datetime(2026, 10, 5, 13, 45)
    assert repr(d.strftime('%Y-%m-%d %H:%M')) == "'2026-10-05 13:45'"
except Exception as ex:
    raise ex
try:
    import datetime
    assert repr(datetime.datetime.strptime('2026-10-05', '%Y-%m-%d').month) == '10'
except Exception as ex:
    raise ex
try:
    import datetime
    d = datetime.datetime(2026, 10, 5)
    assert repr(repr(d.year) + "-" + repr(d.weekday())) == "'2026-0'"
except Exception as ex:
    raise ex
try:
    import datetime
    assert repr(datetime.timedelta(minutes=90) > datetime.timedelta(hours=1)) == 'True'
except Exception as ex:
    raise ex
try:
    import datetime
    assert repr(datetime.datetime(2026, 1, 31).replace(month=3).day) == '31'
except Exception as ex:
    raise ex
try:
    import math
    assert repr(math.floor(-2.5)) == '-3'
except Exception as ex:
    raise ex
try:
    import math
    assert repr(math.ceil(-2.5)) == '-2'
except Exception as ex:
    raise ex
try:
    import math
    assert repr(math.gcd(12, 18)) == '6'
except Exception as ex:
    raise ex
try:
    import math
    assert repr(math.isnan(math.nan)) == 'True'
except Exception as ex:
    raise ex
try:
    import math
    assert repr(repr(math.sqrt(16))) == "'4.0'"
except Exception as ex:
    raise ex
try:
    import math
    assert repr(repr(math.log2(8))) == "'3.0'"
except Exception as ex:
    raise ex
try:
    import math
    assert repr(repr(math.fmod(-7, 3))) == "'-1.0'"
except Exception as ex:
    raise ex
try:
    import math
    assert repr(math.hypot(3, 4)) == '5.0'
except Exception as ex:
    raise ex
assert repr(f"{3.14159:.3g}") == "'3.14'"
assert repr(f'{1234567.891:.2e}') == "'1.23e+06'"
assert repr(f'{0.25:%}') == "'25.000000%'"
assert repr(f'{42:+06d}') == "'+00042'"
assert repr(f'{255:x}|{255:X}|{255:#x}') == "'ff|FF|0xff'"
assert repr(f'{1234567:,}') == "'1,234,567'"
assert repr(f"{'right':>10}.") == "'     right.'"
assert repr(f"{'left':<10}.") == "'left      .'"
assert repr(f"{'mid':^9}.") == "'   mid   .'"
assert repr(f'{-5: d}') == "'-5'"
assert repr(f'{7:b}|{7:o}') == "'111|7'"
assert repr(format(1.5, '.0f')) == "'2'"
assert repr(format(0.0001, '.2f')) == "'0.00'"
try:
    import hashlib
    assert repr(hashlib.sha256(b'abc').hexdigest()[:16]) == "'ba7816bf8f01cfea'"
except Exception as ex:
    raise ex
try:
    import hashlib
    assert repr(hashlib.md5(b'').hexdigest()) == "'d41d8cd98f00b204e9800998ecf8427e'"
except Exception as ex:
    raise ex
try:
    import hashlib
    assert repr(hashlib.sha256(bytes([0, 255])).hexdigest()[:12]) == "'06eb7d6a69ee'"
except Exception as ex:
    raise ex
try:
    import base64
    assert repr(base64.b64encode(b'hello')) == "b'aGVsbG8='"
except Exception as ex:
    raise ex
try:
    import base64
    assert repr(base64.b64decode(base64.b64encode(b'round trip'))) == "b'round trip'"
except Exception as ex:
    raise ex
try:
    import base64
    assert repr(base64.b64encode(bytes([254, 255]))) == "b'/v8='"
except Exception as ex:
    raise ex
try:
    import hmac
    import hashlib
    assert repr(hmac.new(b'k', b'm', hashlib.sha256).hexdigest()[:12]) == "'b60090e30522'"
except Exception as ex:
    raise ex
assert repr(b'hi' + b'!') == "b'hi!'"
assert repr(b'abc'[1]) == '98'
assert repr(bytes([104, 105]).decode()) == "'hi'"
assert repr('hi'.encode()) == "b'hi'"
assert repr(b'a,b'.split(b',')) == "[b'a', b'b']"
assert repr(len(bytes(3))) == '3'
try:
    import itertools
    assert repr([k for k, g in itertools.groupby('aaabb')]) == "['a', 'b']"
except Exception as ex:
    raise ex
try:
    import itertools
    assert repr(list(itertools.pairwise([1, 2, 3]))) == '[(1, 2), (2, 3)]'
except Exception as ex:
    raise ex
try:
    import itertools
    assert repr(list(itertools.batched(range(5), 2))) == '[(0, 1), (2, 3), (4,)]'
except Exception as ex:
    raise ex
try:
    import itertools
    assert repr(list(itertools.compress('abc', [1, 0, 1]))) == "['a', 'c']"
except Exception as ex:
    raise ex
try:
    import itertools
    assert repr(list(itertools.dropwhile(lambda x: x < 3, [1, 2, 3, 1, 2]))) == '[3, 1, 2]'
except Exception as ex:
    raise ex
try:
    import itertools
    assert repr(list(itertools.takewhile(lambda x: x < 3, [1, 2, 3, 1]))) == '[1, 2]'
except Exception as ex:
    raise ex
try:
    import itertools
    assert repr(list(itertools.starmap((lambda a: a * 2), [(1,), (2,)]))) == '[2, 4]'
except Exception as ex:
    raise ex
try:
    import itertools
    assert repr(list(itertools.islice(itertools.count(10), 3))) == '[10, 11, 12]'
except Exception as ex:
    raise ex
try:
    import itertools
    assert repr(next(itertools.repeat('x', 3))) == "'x'"
except Exception as ex:
    raise ex
try:
    import functools
    assert repr(functools.reduce(lambda a, b: a * b, [1, 2, 3, 4])) == '24'
except Exception as ex:
    raise ex
try:
    import functools
    assert repr(functools.partial((lambda a, b: a - b), 10)(3)) == '7'
except Exception as ex:
    raise ex
try:
    import textwrap
    assert repr(textwrap.wrap('aa bb cc dd', 8)) == "['aa bb cc', 'dd']"
except Exception as ex:
    raise ex
try:
    import textwrap
    assert repr(textwrap.shorten('lorem ipsum dolor sit amet', 15)) == "'lorem [...]'"
except Exception as ex:
    raise ex
try:
    import textwrap
    assert repr(textwrap.fill('a b c', 5)) == "'a b c'"
except Exception as ex:
    raise ex
try:
    import html
    assert repr(html.escape('<a>&')) == "'&lt;a&gt;&amp;'"
except Exception as ex:
    raise ex
try:
    import urllib.parse as up
    assert repr(up.quote('a b/c?x=1')) == "'a%20b/c%3Fx%3D1'"
except Exception as ex:
    raise ex
try:
    import urllib.parse as up
    assert repr(up.unquote('a%20b%2Fc')) == "'a b/c'"
except Exception as ex:
    raise ex
try:
    import urllib.parse as up
    assert repr(up.urlencode([('q', 'a b')])) == "'q=a+b'"
except Exception as ex:
    raise ex
try:
    d = {'a': 1}
    assert repr(sorted(d.keys())) == "['a']"
except Exception as ex:
    raise ex
try:
    d = {'a': 1}
    assert repr(sorted(d.values())) == '[1]'
except Exception as ex:
    raise ex
try:
    d = {'a': 1, 'b': 2}
    assert repr(sorted(k for k, v in d.items() if v == 2)) == "['b']"
except Exception as ex:
    raise ex
try:
    d1 = {'a': 1}
    d2 = {'b': 2}
    d1.update(d2)
    assert repr(sorted(d1.keys())) == "['a', 'b']"
except Exception as ex:
    raise ex
assert repr('{} {}!'.format('hi', 'yo')) == "'hi yo!'"
assert repr('{1}{0}'.format('a', 'b')) == "'ba'"
assert repr('{x}{y}'.format(x=1, y=2)) == "'12'"
assert repr('{:.1f}'.format(2.25)) == "'2.2'"
assert repr('{{literal}}'.format()) == "'{literal}'"
assert repr(len('\t\n\\')) == '3'
assert repr('A\x41') == "'AA'"
assert repr(r'a\nb') == "'a\\\\nb'"
assert repr(list(zip([1, 2, 3], 'ab'))) == "[(1, 'a'), (2, 'b')]"
assert repr(list(enumerate('ab', 10))) == "[(10, 'a'), (11, 'b')]"
assert repr(list(reversed([1, 2, 3]))) == '[3, 2, 1]'
assert repr(divmod(divmod(7, 2)[0], 2)) == '(1, 1)'

True
