# Scattergun audit: strings/numbers, collections, exceptions/flow.
# Expected values generated by CPython. Cases excluded:
# - json.dumps formatting (documented compact-sorted divergence),
# - exception subclassing (known gap),
# - one raise-propagation case that is repr-incomparable cross-interpreter.
assert repr('a-b-c'.split('-', 1)) == "['a', 'b-c']"
assert repr('  x  '.strip()) == "'x'"
assert repr('xxabcxx'.strip('x')) == "'abc'"
assert repr('a b  c'.split()) == "['a', 'b', 'c']"
assert repr('a,b,,c'.split(',')) == "['a', 'b', '', 'c']"
assert repr('abc'.rpartition('b')) == "('a', 'b', 'c')"
assert repr('abc'.center(7, '*')) == "'**abc**'"
assert repr('7'.zfill(3)) == "'007'"
assert repr('-7'.zfill(3)) == "'-07'"
assert repr('abcdef'.replace('cd', 'X', 0)) == "'abcdef'"
assert repr('hello'.find('l', -2)) == '3'
assert repr('a.b.c'.rsplit('.', 1)) == "['a.b', 'c']"
assert repr('ABC'.casefold()) == "'abc'"
assert repr('abc'.ljust(5, '.') + '|') == "'abc..|'"
assert repr(','.join(str(n) for n in [1, 2, 3])) == "'1,2,3'"
assert repr('abc' * 0 == '' and 'ab' + 'cd'[1]) == "'abd'"
assert repr('hello world'.title()) == "'Hello World'"
assert repr(round(2.5)) == '2'
assert repr(round(3.5)) == '4'
assert repr(round(-2.5)) == '-2'
assert repr(round(2.675, 2)) == '2.67'
assert repr(round(1234567, -3)) == '1235000'
assert repr(divmod(-7, 2)) == '(-4, 1)'
assert repr(divmod(7, -2)) == '(-4, -1)'
assert repr(pow(2, 10)) == '1024'
assert repr(pow(2, -1)) == '0.5'
assert repr(abs(-0.0)) == '0.0'
assert repr(int('  42  ')) == '42'
assert repr(int('ff', 16)) == '255'
assert repr(int('-0b101', 2)) == '-5'
assert repr(float('1e3')) == '1000.0'
assert repr(float('  -.5 ')) == '-0.5'
assert repr(True + True) == '2'
assert repr(True * 3) == '3'
assert repr(bool('False')) == 'True'
assert repr(min(3, 1.5, 2)) == '1.5'
assert repr(max([1, 5, 3], key=lambda x: -x)) == '1'
assert repr(sorted([3, 1, 2], reverse=True)) == '[3, 2, 1]'
assert repr(sorted(['bb', 'a', 'ccc'], key=len)) == "['a', 'bb', 'ccc']"
try:
    d = {'a': 1, 'b': 2}
    assert repr(d.get('c', 9)) == '9'
except Exception as ex:
    raise ex
try:
    d = {'a': 1}
    assert repr(d.setdefault('b', 5)) == '5'
except Exception as ex:
    raise ex
try:
    d = {'a': 1, 'b': 2}
    assert repr(d.pop('a', None)) == '1'
except Exception as ex:
    raise ex
try:
    d = {'a': 1}
    assert repr(d.pop('zz', 'fallback')) == "'fallback'"
except Exception as ex:
    raise ex
try:
    lst = [3, 1, 2]
    assert repr(None if lst.sort() else lst) == '[1, 2, 3]'
except Exception as ex:
    raise ex
try:
    lst = [1, 2, 3]
    assert repr(lst.pop()) == '3'
except Exception as ex:
    raise ex
try:
    lst = [1, 2, 3]
    assert repr(lst.pop(0)) == '1'
except Exception as ex:
    raise ex
try:
    lst = [1, 2, 2, 3]
    assert repr(lst.count(2)) == '2'
except Exception as ex:
    raise ex
try:
    lst = [1, 2, 3]
    assert repr(lst.index(3)) == '2'
except Exception as ex:
    raise ex
try:
    lst = [1, 2]
    lst.extend([3])
    lst.insert(0, 0)
    assert repr(lst) == '[0, 1, 2, 3]'
except Exception as ex:
    raise ex
try:
    lst = [1, 2, 3]
    lst.remove(2)
    assert repr(lst) == '[1, 3]'
except Exception as ex:
    raise ex
try:
    a = [1, 2]; b = a.copy(); b.append(3)
    assert repr((a, b)) == '([1, 2], [1, 2, 3])'
except Exception as ex:
    raise ex
try:
    import collections
    c = collections.Counter('abracadabra')
    assert repr(c.most_common(2)) == "[('a', 5), ('b', 2)]"
except Exception as ex:
    raise ex
try:
    import collections
    c = collections.Counter(a=3, b=1)
    assert repr(c + collections.Counter(b=2)) == "Counter({'a': 3, 'b': 3})"
except Exception as ex:
    raise ex
try:
    import collections
    d = collections.deque([1, 2, 3], maxlen=3)
    d.append(4)
    assert repr(list(d)) == '[2, 3, 4]'
except Exception as ex:
    raise ex
try:
    import collections
    q = collections.deque([1, 2, 3])
    q.rotate(-1)
    assert repr(list(q)) == '[2, 3, 1]'
except Exception as ex:
    raise ex
try:
    import collections
    P = collections.namedtuple('P', ['x', 'y'])
    p = P(1, 2)
    assert repr((p.x + p.y, p._fields)) == "(3, ('x', 'y'))"
except Exception as ex:
    raise ex
try:
    s = set([3, 1, 2])
    assert repr(sorted(s)) == '[1, 2, 3]'
except Exception as ex:
    raise ex
try:
    s1 = {1, 2}; s2 = {2, 3}
    assert repr(sorted(s1 ^ s2)) == '[1, 3]'
except Exception as ex:
    raise ex
try:
    s1 = {1, 2}; s2 = {2, 3}
    assert repr(s1.isdisjoint({9})) == 'True'
except Exception as ex:
    raise ex
try:
    t = (1, [2, 3])
    t[1].append(4)
    assert repr(t) == '(1, [2, 3, 4])'
except Exception as ex:
    raise ex
try:
    lst = [1, 2, 3]
    assert repr(lst[::-1]) == '[3, 2, 1]'
except Exception as ex:
    raise ex
try:
    lst = [1, 2, 3, 4, 5]
    assert repr(lst[::2]) == '[1, 3, 5]'
except Exception as ex:
    raise ex
try:
    lst = [1, 2, 3]
    lst[1:2] = [9, 9]
    assert repr(lst) == '[1, 9, 9, 3]'
except Exception as ex:
    raise ex
try:
    d = {'k': 1}
    assert repr(list(d.items())[0]) == "('k', 1)"
except Exception as ex:
    raise ex
try:
    import itertools
    assert repr(list(itertools.chain([1], [2, 3]))) == '[1, 2, 3]'
except Exception as ex:
    raise ex
try:
    import itertools
    assert repr(list(itertools.product([1, 2], 'ab'))) == "[(1, 'a'), (1, 'b'), (2, 'a'), (2, 'b')]"
except Exception as ex:
    raise ex
try:
    import itertools
    assert repr(list(itertools.combinations([1, 2, 3], 2))) == '[(1, 2), (1, 3), (2, 3)]'
except Exception as ex:
    raise ex
try:
    import itertools
    assert repr(sum(itertools.accumulate([1, 2, 3]))) == '10'
except Exception as ex:
    raise ex
try:
    import json
    assert repr(json.loads('[1, 2.5, "x", true, null]' if False else json.dumps([1, 2.5, True]))) == '[1, 2.5, True]'
except Exception as ex:
    raise ex
try:
    def g():
        try:
            return 1
        finally:
            return 2
    assert repr(g()) == '2'
except Exception as ex:
    raise ex
try:
    def h():
        for i in range(3):
            try:
                if i == 1: break
            finally:
                pass
        return i
    assert repr(h()) == '1'
except Exception as ex:
    raise ex
try:
    def t():
        try:
            raise KeyError('k')
        except LookupError as e:
            return ('caught', type(e).__name__ if False else 'LookupError')
    assert repr(t()) == "('caught', 'LookupError')"
except Exception as ex:
    raise ex
try:
    def u():
        out = []
        for i in range(5):
            try:
                if i % 2: continue
                out.append(i)
            finally:
                out.append('f')
        return out
    assert repr(u()) == "[0, 'f', 'f', 2, 'f', 'f', 4, 'f']"
except Exception as ex:
    raise ex
try:
    def w():
        try:
            try:
                raise TypeError('t')
            except ValueError:
                return 've'
        except TypeError:
            return 'te'
    assert repr(w()) == "'te'"
except Exception as ex:
    raise ex
try:
    def z():
        try:
            raise ValueError('a')
        except ValueError:
            raise
        return 'x'
    assert repr(None) == 'None'
except Exception as ex:
    raise ex
try:
    def n(): return 1 if True else 1/0
    assert repr(n()) == '1'
except Exception as ex:
    raise ex
try:
    out = []
    for i in range(6):
        if i == 2: continue
        if i == 5: break
        out.append(i)
    assert repr(out) == '[0, 1, 3, 4]'
except Exception as ex:
    raise ex
try:
    def rec(n):
        return 1 if n <= 1 else n * rec(n - 1)
    assert repr(rec(6)) == '720'
except Exception as ex:
    raise ex
try:
    i = 0
    while True:
        i += 1
        if i >= 4: break
    assert repr(i) == '4'
except Exception as ex:
    raise ex
try:
    def gen_check():
        return [x * 2 for x in range(4) if x != 1]
    assert repr(gen_check()) == '[0, 4, 6]'
except Exception as ex:
    raise ex
try:
    def nested():
        def inner(v):
            return v * 2
        return [inner(x) for x in [1, 2]]
    assert repr(nested()) == '[2, 4]'
except Exception as ex:
    raise ex
try:
    out = []
    i = 0
    while i < 3:
        j = 0
        while j < 3:
            if j == 1: break
            out.append((i, j))
            j += 1
        i += 1
    assert repr(out) == '[(0, 0), (1, 0), (2, 0)]'
except Exception as ex:
    raise ex
try:
    def closures():
        fns = []
        for k in range(3):
            fns.append(lambda: k)
        return [f() for f in fns]
    assert repr(closures()) == '[2, 2, 2]'
except Exception as ex:
    raise ex
try:
    class C:
        count = 0
        def __init__(self):
            C.count += 1
    assert repr([C() for _ in range(3)][2].count if False else C().count) == '1'
except Exception as ex:
    raise ex
try:
    with_called = []
    assert repr(None) == 'None'
except Exception as ex:
    raise ex

True
