package extlibs

// Library names as constants for easy reference
const (
	RequestsLibraryName       = "requests"
	SysLibraryName            = "sys"
	SecretsLibraryName        = "secrets"
	SubprocessLibraryName     = "subprocess"
	HTMLParserLibraryName     = "html.parser"
	OSLibraryName             = "os"
	OSPathLibraryName         = "os.path"
	PathlibLibraryName        = "pathlib"
	GlobLibraryName           = "glob"
	LoggingLibraryName        = "logging"
	WaitForLibraryName        = "scriptling.wait_for"
	RuntimeHTTPLibraryName    = "scriptling.runtime.http"
	RuntimeKVLibraryName      = "scriptling.runtime.kv"
	RuntimeSyncLibraryName    = "scriptling.runtime.sync"
	RuntimeSandboxLibraryName = "scriptling.runtime.sandbox"
	AILibraryName             = "scriptling.ai"
	MCPLibraryName            = "scriptling.mcp"
	ToonLibraryName           = "scriptling.toon"
	YAMLLibraryName           = "yaml"
	AgentLibraryName          = "scriptling.ai.agent"
	InteractLibraryName       = "scriptling.ai.agent.interact"
	SimilarityLibraryName     = "scriptling.similarity"
	SecretLibraryName         = "scriptling.secret"
	TOMLLibraryName           = "toml"
	WebSocketLibraryName      = "scriptling.net.websocket"
	MulticastLibraryName      = "scriptling.net.multicast"
	UnicastLibraryName        = "scriptling.net.unicast"
	GossipLibraryName         = "scriptling.net.gossip"
	GrepLibraryName           = "scriptling.grep"
	SedLibraryName            = "scriptling.sed"
	ContainerLibraryName      = "scriptling.container"
)
